# Generated by Django 6.0.6 on 2026-06-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_processedwebhook_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_session_id',
            new_name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
